### ISSUE TITLE
What if you already have csv file with everything you need ?

### ISSUE THREAD

**Issue by doubianimehdi** [shaheen-syed/LDA#1]
Hi, 

I was wondering how I could use your pipeline if I already have abstracts , title, year and journals in a csv file ?
Thank you for your help !

Best Regards

**Comment by shaheen-syed** [comment]
You can start with the preprocessing code and rather than reading the PDFs from disk and extracting the title, year, and journal name from the file structure you can simply read in your CSV file with Pandas for instance, and then overwrite the variables journal, year, title, and content. Also make sure to comment out some checks to see if a file has already been processed.

**Comment by doubianimehdi** [comment]
Ok ! Thank you very much ! I'll try that :)
